bases:
  - ../base
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: service3-deployment
    path: deployment-patch.yaml
  - target:
      version: v1
      kind: Service
      name: service3
    path: service-patch.yaml
